export const types = {
  GET_LOGIN: 'GET_LOGIN',
  GET_LOGIN_SUCCESS: 'GET_LOGIN_SUCCESS',
  GET_LOGIN_FAILURE: 'GET_LOGIN_FAILURE',
  GET_LOGIN_RESET: 'GET_LOGIN_RESET',

  GET_SEARCH_MAPS: 'GET_SEARCH_MAPS',
  GET_SEARCH_MAPS_SUCCESS: 'GET_SEARCH_MAPS_SUCCESS',
  GET_SEARCH_MAPS_FAILURE: 'GET_SEARCH_MAPS_FAILURE',
  GET_SEARCH_MAPS_RESET: 'GET_SEARCH_MAPS_RESET',

  GET_SEARCH_PRODUCT: 'GET_SEARCH_PRODUCT',
  GET_PRODUCT: 'GET_PRODUCT',
  GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',
  GET_PRODUCT_RESET: 'GET_PRODUCT_RESET',
};
